version: '3.8'
services:
  frontend:
    container_name: progress-tracker-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - pt_network
networks:
  pt_network:
    driver: bridge