name: Deploy to Production AWS

on:
  push:
    branches:
      - devops
  pull_request:
    branches:
      - devops

jobs:
  deploy:
    name: production deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm          
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}
          
        working-directory: /home/ec2-user/Progress_tracker_frontend_new
        command: npm install
        command: docker compose down 
        command: docker rmi progresstracker-backend:latest
        command: cp .env.production .env
        command: docker build -t progresstracker-backend:latest .
        command: docker compose up -d

#check 